# Generated by Django 4.2.2 on 2023-07-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_created_at_remove_post_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
