# Generated by Django 4.2.2 on 2023-07-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_author_post_created_at_post_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
