# Generated by Django 4.2.2 on 2023-07-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_created_at_remove_post_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryPost',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
