# Generated by Django 4.2.2 on 2023-07-14 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0007_remove_post_category_delete_categorypost_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('display', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='اسلاگ')),
                ('icon', models.CharField(default='bi bi-toggles2', max_length=50, verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی مطلب',
                'verbose_name_plural': 'دسته\u200cبندی مطالب',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=50, verbose_name='نویسنده')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(upload_to='posts/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='اسلاگ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.categorypost', verbose_name='گروه')),
            ],
            options={
                'verbose_name': 'مطلب',
                'verbose_name_plural': 'مطالب',
            },
        ),
    ]
