# Generated by Django 4.2.2 on 2023-07-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_category_post_intro_delete_categorypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feature',
            field=models.BooleanField(default=False, verbose_name='مطلب ویژه'),
        ),
    ]
