# Generated by Django 4.2.2 on 2023-07-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_rename_feature_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='top_post',
            field=models.BooleanField(default=False, verbose_name='مطلب اصلی'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
    ]
