# Generated by Django 4.2.2 on 2023-07-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='نام')),
                ('is_active', models.BooleanField(default=False, verbose_name='تایید شده؟')),
            ],
            options={
                'verbose_name': 'عضویت خبرنامه',
                'verbose_name_plural': 'عضویت خبرنامه',
            },
        ),
    ]
