# Generated by Django 4.2.2 on 2023-07-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_subscribenews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribenews',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
    ]
