# Generated by Django 4.2.2 on 2023-07-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_subscribenews_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribeNews',
        ),
    ]
