# Generated by Django 4.2.2 on 2023-07-04 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('slug', models.SlugField(verbose_name='اسلاگ')),
                ('order', models.BooleanField(default=False, verbose_name='سفارش')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='download_media', verbose_name='تصویر')),
                ('media', models.FileField(blank=True, null=True, storage=product.storage.ProtectedMedia, upload_to='download_media', verbose_name='رسانه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('unit', models.CharField(max_length=150, verbose_name='واحد')),
                ('featured', models.BooleanField(default=False, verbose_name='محصول ویژه؟')),
                ('recent_product', models.BooleanField(default=False, verbose_name='محصول جدید؟')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='دسته\u200cبندی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_title', models.CharField(max_length=50, verbose_name='مشخصه')),
                ('spec_description', models.CharField(max_length=50, verbose_name='توضیحات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مشخصه ',
                'verbose_name_plural': 'مشخصات محصول',
            },
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='product/image', verbose_name='تصویر')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='اسلاگ')),
                ('featured_image', models.BooleanField(default=False, verbose_name='تصویر ویژه؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'تصویر دسته\u200cبندی',
                'verbose_name_plural': 'تصویر دسته\u200cبندی\u200cها',
            },
        ),
    ]
