# Generated by Django 4.2.2 on 2023-07-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_categoryimage_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
    ]
