# Generated by Django 4.2.2 on 2023-07-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryimage',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, verbose_name='اسلاگ'),
            preserve_default=False,
        ),
    ]
