# Generated by Django 4.2.2 on 2023-07-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_categoryimage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='product/image', verbose_name='تصویر'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CategoryImage',
        ),
    ]
