# Generated by Django 4.2.2 on 2023-07-06 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_category_image_delete_categoryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='مشخصه')),
                ('description', models.CharField(max_length=50, verbose_name='توضیحات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مشخصه ',
                'verbose_name_plural': 'مشخصات محصول',
            },
        ),
        migrations.DeleteModel(
            name='ProductSpec',
        ),
    ]
