# Generated by Django 4.2.2 on 2023-07-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_specifications_delete_productspec'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=1, verbose_name='موجود'),
            preserve_default=False,
        ),
    ]
