# Generated by Django 4.2.2 on 2023-07-15 12:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تایید شده؟'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
