# Generated by Django 4.2.2 on 2023-07-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_customproduct_delete_customproductrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customproduct',
            name='full_name',
        ),
    ]
