# Generated by Django 4.2.2 on 2023-07-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_customproduct_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproduct',
            name='reply',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='customproduct',
            name='status',
            field=models.BooleanField(default=False, verbose_name='تایید درخواست'),
        ),
    ]
