# Generated by Django 4.2.1 on 2023-07-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_customproduct_reply_alter_customproduct_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام')),
                ('title', models.CharField(choices=[('RECOMMENT', 'پیشنهاد'), ('CRITIC', 'انتقاد'), ('FOLLOW', 'پیگیری سفارشات'), ('OTHER', 'سایر موضوعات')], max_length=150, verbose_name='عنوان')),
                ('email', models.EmailField(max_length=50, verbose_name='آدرس ایمیل')),
                ('phone_number', models.CharField(max_length=20, verbose_name='آدرس ایمیل')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'تماس',
                'verbose_name_plural': 'تماس\u200cها',
            },
        ),
    ]
