# Generated by Django 4.2.1 on 2023-07-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='description',
            field=models.TextField(verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='title',
            field=models.CharField(choices=[('RECOMMENT', 'پیشنهاد'), ('CRITIC', 'انتقاد'), ('FOLLOW', 'پیگیری'), ('OTHER', 'سایر موضوعات')], max_length=150, verbose_name='عنوان'),
        ),
    ]
