# Generated by Django 4.2.2 on 2023-07-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_contactus_phone_number_alter_contactus_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن پیام')),
            ],
            options={
                'verbose_name': 'درباره ما',
            },
        ),
    ]
