# Generated by Django 4.2.2 on 2023-07-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='display',
            field=models.BooleanField(default=False, verbose_name='نمایش داده شود؟'),
        ),
    ]
