# Generated by Django 4.2.2 on 2023-07-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_aboutus_display'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'درباره ما', 'verbose_name_plural': 'درباه ما'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'پیام', 'verbose_name_plural': 'پیام\u200cها'},
        ),
    ]
