# Generated by Django 4.2.2 on 2023-07-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_shipping_address_alter_payment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ip',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CART', 'کارت به کارت')], default='CART', max_length=50, verbose_name='روش پرداخت'),
        ),
    ]
