# Generated by Django 4.2.2 on 2023-07-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_order_country_remove_order_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cart_id',
            field=models.CharField(default=1, max_length=16, verbose_name='شماره کارت '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در دست بررسی'), ('APPROVED', 'تایید شده')], default='PENDING', max_length=50, verbose_name='وضعیت'),
        ),
    ]
