# Generated by Django 4.2.2 on 2023-07-09 05:56

import checkout.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_remove_order_payment_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[(checkout.models.PaymentStatus['PENDING'], 'در دست بررسی'), (checkout.models.PaymentStatus['APPROVED'], 'تایید شده'), (checkout.models.PaymentStatus['REJECTED'], 'رد شده')], default='PENDING', max_length=50, verbose_name='وضعیت'),
        ),
    ]
