# Generated by Django 4.2.2 on 2023-07-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_alter_order_shipping_address_alter_order_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(max_length=100, verbose_name='آدرس گیرنده'),
        ),
    ]
