# Generated by Django 4.2.2 on 2023-07-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_alter_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.BooleanField(default=False, verbose_name='ارسال شده'),
        ),
    ]
