# Generated by Django 4.2.2 on 2023-07-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_order_payment_status_order_shipping_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False, max_length=50, verbose_name='تایید شده'),
        ),
    ]
