# Generated by Django 4.2.2 on 2023-07-11 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryservice',
            options={'verbose_name': 'دسته\u200cبندی خدمت', 'verbose_name_plural': 'دسته\u200cبندی خدمات'},
        ),
        migrations.AddField(
            model_name='categoryservice',
            name='icon',
            field=models.CharField(default='bi bi-toggles2', max_length=50, verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='service.categoryservice', verbose_name='گروه'),
        ),
    ]
