# Generated by Django 4.2.2 on 2023-07-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_categoryservice_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryservice',
            name='display',
            field=models.BooleanField(default=True, verbose_name='نمایش داده شود؟'),
        ),
    ]
